language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/c9eda12b4806fba3931f7b791be7a672c92d9ca0.zip
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover -v tests
notifications:
  email:
      - brett.olsen+travis-ci@gmail.com
      - robert.kern+travis-ci@gmail.com
