language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/177dbe83d5c7551cb2cad790cb5a963b54cf19ef.zip
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover -v tests
notifications:
  email:
      - brett.olsen+travis-ci@gmail.com
      - robert.kern+travis-ci@gmail.com
