language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/d902b7cf24eba5bc5be9e8001d639abd912adf6d.zip
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover -v tests
notifications:
  email:
      - brett.olsen+travis-ci@gmail.com
      - robert.kern+travis-ci@gmail.com
